### ISSUE TITLE
escaping of characters that are not accepted by filesystems

### ISSUE THREAD

**Issue by Cathryne** [sebpearce/firewood#1]
Hello and thank you for this neat app!

In many cases it has helped me a lot to organise my Kindle clippings :-)   However, in case a book title contains `()`, `:`, `&` and other such special characters, the resulting text files can't be copied from the Kindle to a Win7 PC without manual renaming. A Mac with 10.9 was more permissive, but I guess it also can't handle all some characters in filename.

In order to avoid such problems, some kind of automatic removal of these characters, or conversion to less special ones would IMHO be worthwhile to implement.

Thanks and greetings!

**Comment by Cathryne** [comment]
PS: I found the following (apparently official) lists of unsupported characters.
https://support.microsoft.com/kb/905231
https://support.apple.com/kb/HT5923

**Comment by sebpearce** [comment]
Thanks for pointing that out! I hadn't considered that the filenames would be a problem with Windows.

Also thank you for linking to the character lists, that helps a lot. :) I'll see if I can replace the unsupported characters with alternatives.

**Comment by sebpearce** [comment]
Hi Cathryne,

I've rewritten Firewood in Python and made some alterations so that it outputs Windows-friendly filenames. It's called `pyrewood.py`: https://github.com/sebpearce/firewood/blob/master/pyrewood.py

The script is far from perfect but it does what it's supposed to and can be used instead of the C version.

Thanks again for the idea.

**Comment by Cathryne** [comment]
Works perfectly on Mac, thank you :-) I'll test it on Windows 7 this week.

**Comment by Cathryne** [comment]
The results files look a bit denser, because Win7 seems to treat the `\n` differently from Mac OS X, but everything is still readable.
